apiVersion: v2
name: ecommerce-api
description: Helm chart for E-Commerce Product API
type: application
version: 1.0.0
appVersion: "1.0.0"
maintainers:
  - name: Pouya Arjmandiakram
    email: arjomandipouya1051@gmail.com
